---
- name: Install Grafana on Linux
  hosts: localhost
  become: yes
  tasks:
    - name: Add Grafana GPG key
      rpm_key:
        state: present
        key: https://packages.grafana.com/gpg.key

    - name: Add Grafana repository
      yum_repository:
        name: grafana
        description: Grafana Repository
        baseurl: https://packages.grafana.com/oss/rpm
        gpgcheck: yes
        enabled: yes

    - name: Install Grafana
      yum:
        name: grafana
        state: present

    - name: Start and enable Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
